# Generated by Django 5.0.6 on 2024-06-04 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='businesses/logos')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='App.businesstype')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
            },
        ),
    ]
