# Generated by Django 5.0.6 on 2024-06-06 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_service_unique_service_per_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerole',
            name='business_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_role', to='App.businesstype'),
            preserve_default=False,
        ),
    ]
