# Generated by Django 5.0.6 on 2024-06-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='workday',
        ),
    ]
