# Generated by Django 5.0.6 on 2024-06-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_remove_order_workday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
